apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operatorgroup-fruitscatalog
  annotations:
    olm.providedAPIs: Alertmanager.v1.monitoring.coreos.com,Grafana.v1alpha1.integreatly.org,GrafanaDashboard.v1alpha1.integreatly.org,GrafanaDataSource.v1alpha1.integreatly.org,PodMonitor.v1.monitoring.coreos.com,Prometheus.v1.monitoring.coreos.com,PrometheusRule.v1.monitoring.coreos.com,ServiceMonitor.v1.monitoring.coreos.com
  generateName: fruits-catalog-prod-
  namespace: fruits-catalog-prod
spec:
  targetNamespaces:
  - fruits-catalog-prod