kind: ConfigMap
apiVersion: v1
metadata:
  name: backend-config
  labels:
    app: fruits-catalog
    deployment: backend
data:
  application.yml: |-
    spring.data.mongodb.uri: mongodb://${MONGODB_DATABASE_USER}:${MONGODB_DATABASE_PASSWORD}@mongodb:27017/sampledb